#ifndef MEM_SERVICE_OBJECT_CONTRACT_H
#define MEM_SERVICE_OBJECT_CONTRACT_H

#define MEM_SERVICE_OBMM_SERVICE_OBJECT_BYTES 8192ULL
#define MEM_SERVICE_OBMM_WEIGHT_OFFSET 0x10000ULL
#define MEM_SERVICE_OBMM_KVCACHE_OFFSET 0x14000ULL
#define MEM_SERVICE_OBMM_HIDDEN_RANGE_INPUT_OFFSET 0x18000ULL
#define MEM_SERVICE_OBMM_HIDDEN_RANGE_OUTPUT_OFFSET 0x58000ULL
#define MEM_SERVICE_OBMM_HIDDEN_RANGE_RUNTIME_OUTPUT_OFFSET 0x98000ULL
#define MEM_SERVICE_OBMM_QWEN3_ROUND_DONE_OFFSET 0xda000ULL
#define MEM_SERVICE_OBMM_QWEN3_ROUND_DONE_SLOTS 1024ULL
#define MEM_SERVICE_OBMM_QWEN3_DYNAMIC_ARENA_OFFSET 0x100000ULL
#define MEM_SERVICE_OBMM_QWEN3_KV_STATE_OFFSET 0x100000ULL
#define MEM_SERVICE_OBMM_QWEN3_KV_STATE_SLOT_BYTES 0x200000ULL
#define MEM_SERVICE_OBMM_QWEN3_KV_STATE_BLOCK_TIER0_BYTES 0x40000ULL
#define MEM_SERVICE_OBMM_QWEN3_KV_STATE_BLOCK_TIER1_BYTES 0x80000ULL
#define MEM_SERVICE_OBMM_QWEN3_KV_STATE_BLOCK_TIER2_BYTES 0x100000ULL
#define MEM_SERVICE_OBMM_QWEN3_KV_STATE_BLOCK_TIER3_BYTES \
    MEM_SERVICE_OBMM_QWEN3_KV_STATE_SLOT_BYTES
#define MEM_SERVICE_OBMM_QWEN3_KV_STATE_SLOTS 32ULL
#define MEM_SERVICE_OBMM_QWEN3_RUNTIME_RANGE_OUTPUT_SLOTS 32ULL
#define MEM_SERVICE_OBMM_QWEN3_RUNTIME_RANGE_OUTPUT_OFFSET \
    (MEM_SERVICE_OBMM_QWEN3_KV_STATE_OFFSET + \
     (MEM_SERVICE_OBMM_QWEN3_KV_STATE_SLOT_BYTES * \
      MEM_SERVICE_OBMM_QWEN3_KV_STATE_SLOTS))
#define MEM_SERVICE_OBMM_QWEN3_RUNTIME_RANGE_OUTPUT_REGION_BYTES \
    (MEM_SERVICE_OBMM_QWEN3_RUNTIME_RANGE_OUTPUT_SLOTS * \
     MEM_SERVICE_OBMM_HIDDEN_RANGE_BYTES)
#define MEM_SERVICE_OBMM_QWEN3_ENGRAM_BASE_OFFSET \
    (MEM_SERVICE_OBMM_QWEN3_RUNTIME_RANGE_OUTPUT_OFFSET + \
     MEM_SERVICE_OBMM_QWEN3_RUNTIME_RANGE_OUTPUT_REGION_BYTES)
#define MEM_SERVICE_OBMM_QWEN3_ENGRAM_SLOT_BYTES 0x4000ULL
#define MEM_SERVICE_OBMM_QWEN3_ENGRAM_HISTORY_BYTES 0x2000ULL
#define MEM_SERVICE_OBMM_QWEN3_ENGRAM_CANDIDATES_BYTES 256ULL
#define MEM_SERVICE_OBMM_QWEN3_ENGRAM_SELECTED_BYTES 64ULL
#define MEM_SERVICE_OBMM_QWEN3_ENGRAM_STATE_BYTES 128ULL
#define MEM_SERVICE_OBMM_HIDDEN_RANGE_BYTES 262144ULL
#ifndef MEM_SERVICE_OBMM_QWEN3_TOKEN_RESULT_BYTES
#define MEM_SERVICE_OBMM_QWEN3_TOKEN_RESULT_BYTES 64ULL
#endif
#define MEM_SERVICE_OBMM_QWEN3_ROUND_DONE_BYTES 64ULL
#define MEM_SERVICE_OBMM_QWEN3_ROUND_DONE_REGION_BYTES \
    (MEM_SERVICE_OBMM_QWEN3_ROUND_DONE_SLOTS * \
     MEM_SERVICE_OBMM_QWEN3_ROUND_DONE_BYTES)
#define MEM_SERVICE_OBMM_KIND_WEIGHT_TILE 1U
#define MEM_SERVICE_OBMM_KIND_KVCACHE_BLOCK 2U
#define MEM_SERVICE_OBMM_KIND_HIDDEN_RANGE_INPUT 3U
#define MEM_SERVICE_OBMM_KIND_HIDDEN_RANGE_OUTPUT 4U
#define MEM_SERVICE_OBMM_KIND_HIDDEN_RANGE_RUNTIME_OUTPUT 5U
#ifndef MEM_SERVICE_OBMM_KIND_QWEN3_TOKEN_RESULT
#define MEM_SERVICE_OBMM_KIND_QWEN3_TOKEN_RESULT 6U
#endif
#define MEM_SERVICE_OBMM_KIND_QWEN3_KV_STATE 7U
#define MEM_SERVICE_OBMM_KIND_QWEN3_ENGRAM_HISTORY 8U
#define MEM_SERVICE_OBMM_KIND_QWEN3_ENGRAM_CANDIDATES 9U
#define MEM_SERVICE_OBMM_KIND_QWEN3_ENGRAM_SELECTED 10U
#define MEM_SERVICE_OBMM_KIND_QWEN3_ENGRAM_STATE 11U
#define MEM_SERVICE_OBMM_KIND_SERVING_REQUEST 12U

/*
 * Model-neutral layout aliases for core use. Values mirror the QWEN3 layout
 * exactly (Qwen3 is the only registered profile in stage 0). Core .c/.h
 * files use these names instead of the MEM_SERVICE_OBMM_QWEN3_* compat
 * macros so the core stays free of model names. The QWEN3_* macros are
 * retained for adapter/test compatibility; real layout parameterization is
 * deferred to stage 1.
 */
#define MEM_SERVICE_OBMM_DYNAMIC_ARENA_OFFSET \
    MEM_SERVICE_OBMM_QWEN3_DYNAMIC_ARENA_OFFSET
#define MEM_SERVICE_OBMM_KV_STATE_OFFSET \
    MEM_SERVICE_OBMM_QWEN3_KV_STATE_OFFSET
#define MEM_SERVICE_OBMM_KV_STATE_SLOT_BYTES \
    MEM_SERVICE_OBMM_QWEN3_KV_STATE_SLOT_BYTES
#define MEM_SERVICE_OBMM_ROUND_DONE_OFFSET \
    MEM_SERVICE_OBMM_QWEN3_ROUND_DONE_OFFSET
#define MEM_SERVICE_OBMM_ROUND_DONE_SLOTS \
    MEM_SERVICE_OBMM_QWEN3_ROUND_DONE_SLOTS
#define MEM_SERVICE_OBMM_ROUND_DONE_BYTES \
    MEM_SERVICE_OBMM_QWEN3_ROUND_DONE_BYTES
#define MEM_SERVICE_OBMM_ROUND_DONE_REGION_BYTES \
    MEM_SERVICE_OBMM_QWEN3_ROUND_DONE_REGION_BYTES
#define MEM_SERVICE_OBMM_PIPELINE_READY_BYTES 64ULL
#define MEM_SERVICE_OBMM_PIPELINE_READY_OFFSET \
    (MEM_SERVICE_OBMM_ROUND_DONE_OFFSET + \
     MEM_SERVICE_OBMM_ROUND_DONE_REGION_BYTES - \
     MEM_SERVICE_OBMM_PIPELINE_READY_BYTES)
#define MEM_SERVICE_OBMM_KIND_MODEL_TOKEN_RESULT \
    MEM_SERVICE_OBMM_KIND_QWEN3_TOKEN_RESULT
#define MEM_SERVICE_OBMM_MODEL_TOKEN_RESULT_BYTES \
    MEM_SERVICE_OBMM_QWEN3_TOKEN_RESULT_BYTES
#define MEM_SERVICE_OBMM_KIND_MODEL_KV_STATE \
    MEM_SERVICE_OBMM_KIND_QWEN3_KV_STATE
#define MEM_SERVICE_OBMM_KIND_MODEL_ENGRAM_HISTORY \
    MEM_SERVICE_OBMM_KIND_QWEN3_ENGRAM_HISTORY
#define MEM_SERVICE_OBMM_KIND_MODEL_ENGRAM_CANDIDATES \
    MEM_SERVICE_OBMM_KIND_QWEN3_ENGRAM_CANDIDATES
#define MEM_SERVICE_OBMM_KIND_MODEL_ENGRAM_SELECTED \
    MEM_SERVICE_OBMM_KIND_QWEN3_ENGRAM_SELECTED
#define MEM_SERVICE_OBMM_KIND_MODEL_ENGRAM_STATE \
    MEM_SERVICE_OBMM_KIND_QWEN3_ENGRAM_STATE

#endif
