import torch
from simpler.task_interface import TaskArgs, TensorArgType
from simpler_setup.torch_interop import make_tensor_arg

def _alloc_intermediates(tensors):
    pass

def host_orch(orch, _args, config, *, tensors, callables, sub_ids, _keep, contexts):
    has_prefill__ssa_v0 = tensors["has_prefill__ssa_v0"]
    if has_prefill__ssa_v0:
        _ta_0 = TaskArgs()
        _ta_0.add_tensor(make_tensor_arg(tensors["prefill_hidden__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["prefill_seq_lens__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["input_rms_weight__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["wq__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["wk__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["wv__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["q_norm_weight__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["k_norm_weight__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["rope_cos__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["rope_sin__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["block_table__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["prefill_slot_mapping__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["k_cache_all__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["v_cache_all__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["wo__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["post_rms_weight__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["w_gate__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["w_up__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["w_down__ssa_v0"]), TensorArgType.INPUT)
        _ta_0.add_tensor(make_tensor_arg(tensors["prefill_out__ssa_v0"]), TensorArgType.OUTPUT_EXISTING)
        _keep.append(_ta_0)
        orch.submit_next_level(callables["qwen3_prefill_all"], _ta_0, config)
    _ta_1 = TaskArgs()
    _ta_1.add_tensor(make_tensor_arg(tensors["decode_hidden__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["input_rms_weight__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["wq__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["wk__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["wv__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["q_norm_weight__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["k_norm_weight__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["decode_seq_lens__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["block_table__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["decode_slot_mapping__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["rope_cos__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["rope_sin__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["k_cache_all__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["v_cache_all__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["wo__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["post_rms_weight__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["w_gate__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["w_up__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["w_down__ssa_v0"]), TensorArgType.INPUT)
    _ta_1.add_tensor(make_tensor_arg(tensors["decode_out__ssa_v0"]), TensorArgType.OUTPUT_EXISTING)
    _keep.append(_ta_1)
    orch.submit_next_level(callables["qwen3_decode_all"], _ta_1, config)
    tensors["out_d__ssa_v0"] = tensors["decode_out__ssa_v0"]
    _ta_2 = TaskArgs()
    _ta_2.add_tensor(make_tensor_arg(tensors["rms_x__ssa_v0"]), TensorArgType.INPUT)
    _ta_2.add_tensor(make_tensor_arg(tensors["final_norm_weight__ssa_v0"]), TensorArgType.INPUT)
    _ta_2.add_tensor(make_tensor_arg(tensors["lm_head_weight_t__ssa_v0"]), TensorArgType.INPUT)
    _ta_2.add_tensor(make_tensor_arg(tensors["rms_normed__ssa_v0"]), TensorArgType.OUTPUT_EXISTING)
    _ta_2.add_tensor(make_tensor_arg(tensors["logits_padded__ssa_v0"]), TensorArgType.OUTPUT_EXISTING)
    _keep.append(_ta_2)
    orch.submit_next_level(callables["qwen3_rms_lmhead"], _ta_2, config)
    tensors["out_rms__ssa_v0"] = tensors["rms_normed__ssa_v0"]
    tensors["out_lm__ssa_v0"] = tensors["logits_padded__ssa_v0"]
    _ta_3 = TaskArgs()
    _ta_3.add_tensor(make_tensor_arg(tensors["out_lm__ssa_v0"]), TensorArgType.INPUT)
    _ta_3.add_tensor(make_tensor_arg(tensors["decode_seq_lens__ssa_v0"]), TensorArgType.INPUT)
    _ta_3.add_tensor(make_tensor_arg(tensors["decode_slot_mapping__ssa_v0"]), TensorArgType.INPUT)
    _ta_3.add_tensor(make_tensor_arg(tensors["decode_hidden__ssa_v0"]), TensorArgType.OUTPUT_EXISTING)
    orch.submit_sub(sub_ids["sample_and_prepare"], _ta_3)
    tensors["upd_hidden__ssa_v0"] = tensors["decode_hidden__ssa_v0"]
    for ___idx_v0 in range(0, 9, 1):
        _ta_4 = TaskArgs()
        _ta_4.add_tensor(make_tensor_arg(tensors["upd_hidden__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["input_rms_weight__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["wq__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["wk__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["wv__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["q_norm_weight__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["k_norm_weight__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["decode_seq_lens__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["block_table__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["decode_slot_mapping__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["rope_cos__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["rope_sin__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["k_cache_all__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["v_cache_all__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["wo__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["post_rms_weight__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["w_gate__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["w_up__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["w_down__ssa_v0"]), TensorArgType.INPUT)
        _ta_4.add_tensor(make_tensor_arg(tensors["out_d__ssa_v0"]), TensorArgType.OUTPUT_EXISTING)
        _keep.append(_ta_4)
        orch.submit_next_level(callables["qwen3_decode_all"], _ta_4, config)
        tensors["out_d__ssa_v3"] = tensors["out_d__ssa_v0"]
        _ta_5 = TaskArgs()
        _ta_5.add_tensor(make_tensor_arg(tensors["rms_x__ssa_v0"]), TensorArgType.INPUT)
        _ta_5.add_tensor(make_tensor_arg(tensors["final_norm_weight__ssa_v0"]), TensorArgType.INPUT)
        _ta_5.add_tensor(make_tensor_arg(tensors["lm_head_weight_t__ssa_v0"]), TensorArgType.INPUT)
        _ta_5.add_tensor(make_tensor_arg(tensors["out_rms__ssa_v0"]), TensorArgType.OUTPUT_EXISTING)
        _ta_5.add_tensor(make_tensor_arg(tensors["out_lm__ssa_v0"]), TensorArgType.OUTPUT_EXISTING)
        _keep.append(_ta_5)
        orch.submit_next_level(callables["qwen3_rms_lmhead"], _ta_5, config)
        tensors["out_rms__ssa_v3"] = tensors["out_rms__ssa_v0"]
        tensors["out_lm__ssa_v3"] = tensors["out_lm__ssa_v0"]
        _ta_6 = TaskArgs()
        _ta_6.add_tensor(make_tensor_arg(tensors["out_lm__ssa_v3"]), TensorArgType.INPUT)
        _ta_6.add_tensor(make_tensor_arg(tensors["decode_seq_lens__ssa_v0"]), TensorArgType.INPUT)
        _ta_6.add_tensor(make_tensor_arg(tensors["decode_slot_mapping__ssa_v0"]), TensorArgType.INPUT)
        _ta_6.add_tensor(make_tensor_arg(tensors["upd_hidden__ssa_v0"]), TensorArgType.OUTPUT_EXISTING)
        orch.submit_sub(sub_ids["sample_and_prepare"], _ta_6)
        tensors["upd_hidden__ssa_v3"] = tensors["upd_hidden__ssa_v0"]

