#!/bin/zsh
set -euo pipefail
setopt null_glob

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GUEST_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WORKSPACE_ROOT="$(cd "$GUEST_ROOT/../.." && pwd)"
LAUNCHER="$SCRIPT_DIR/launch_ub_eight_node_headless.sh"
VALIDATOR="$SCRIPT_DIR/validate_lingqu_shmem_pto_eight_node.py"
ARTIFACT_SNAPSHOTTER="$SCRIPT_DIR/snapshot_simpler_host_artifacts.py"
MANIFEST=""
SOURCE_MANIFEST=""
SCENARIO="$WORKSPACE_ROOT/scenarios/mvp_8host_single_domain.yaml"
SIM_CLI_BIN="${SIM_CLI_BIN:-$WORKSPACE_ROOT/target/release/sim-cli}"
KERNEL_IMAGE="${KERNEL_IMAGE:-$GUEST_ROOT/out/Image}"
INITRAMFS_IMAGE="${INITRAMFS_IMAGE:-$GUEST_ROOT/out/initramfs.cpio.gz}"
QEMU_BUILD_DIR="${QEMU_UB_BUILD_DIR:-$WORKSPACE_ROOT/vendor/qemu_8.2.0_ub/build}"
LAYOUT=nd
ELEMENTS=16384
TOKEN_VALUE=0
TIMEOUT_MS=240000
CNA_BASE=0xf001
MAX_RUNTIME=600
QEMU_MEM="${QEMU_MEM:-8G}"
QEMU_SMP="${QEMU_SMP:-2}"
RUN_ID="lingqu-shmem-pto-eight-$(date +%Y%m%dT%H%M%S)-${RANDOM}"
EVIDENCE_DIR=""

usage() {
  cat <<'USAGE'
Usage: run_ub_eight_node_lingqu_shmem_pto_direct.sh [options]

Required:
  --manifest PATH        Simpler host-vector artifact manifest.

Options:
  --scenario PATH        Eight-host simulator scenario.
  --sim-cli-bin PATH     sim-cli used for artifact fingerprinting.
  --kernel-image PATH    Arm64 guest kernel image.
  --initramfs-image PATH Guest initramfs with the PTO workload.
  --layout LAYOUT        PTO UB_GM layout; functional demo requires nd.
  --elements N           Elements per consumer; ND requires 16384.
  --generation N         OBMM bootstrap generation; generated by default.
  --token-value N        OBMM import token value.
  --timeout-ms N         Guest producer/consumer deadline.
  --cna-base N           Node A PTO device CNA; default 0xf001.
  --max-runtime N        Host runner deadline in seconds.
  --qemu-mem SIZE        Memory for each QEMU; default 8G. This preserves a
                         contiguous 2 MiB OBMM export after guest boot.
  --qemu-smp N           vCPUs for each QEMU; default 2.
  --run-id ID            Stable evidence and log identifier.
  --evidence-dir PATH    New, non-existing evidence directory.
  -h, --help             Show this help.
USAGE
}

require_value() {
  if [[ "$2" -lt 2 ]]; then
    echo "$1 requires a value" >&2
    exit 2
  fi
}

canonical_file() {
  local label="$1"
  local input_path="$2"

  if [[ ! -f "$input_path" ]]; then
    echo "$label does not exist: $input_path" >&2
    exit 2
  fi
  printf '%s/%s\n' \
    "$(cd "$(dirname "$input_path")" && pwd)" \
    "$(basename "$input_path")"
}

hash_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1"
  else
    shasum -a 256 "$1"
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --manifest)
      require_value "$1" "$#"
      MANIFEST="$2"
      shift 2
      ;;
    --scenario)
      require_value "$1" "$#"
      SCENARIO="$2"
      shift 2
      ;;
    --sim-cli-bin)
      require_value "$1" "$#"
      SIM_CLI_BIN="$2"
      shift 2
      ;;
    --kernel-image)
      require_value "$1" "$#"
      KERNEL_IMAGE="$2"
      shift 2
      ;;
    --initramfs-image)
      require_value "$1" "$#"
      INITRAMFS_IMAGE="$2"
      shift 2
      ;;
    --layout)
      require_value "$1" "$#"
      LAYOUT="$2"
      shift 2
      ;;
    --elements)
      require_value "$1" "$#"
      ELEMENTS="$2"
      shift 2
      ;;
    --generation)
      require_value "$1" "$#"
      GENERATION="$2"
      shift 2
      ;;
    --token-value)
      require_value "$1" "$#"
      TOKEN_VALUE="$2"
      shift 2
      ;;
    --timeout-ms)
      require_value "$1" "$#"
      TIMEOUT_MS="$2"
      shift 2
      ;;
    --cna-base)
      require_value "$1" "$#"
      CNA_BASE="$2"
      shift 2
      ;;
    --max-runtime)
      require_value "$1" "$#"
      MAX_RUNTIME="$2"
      shift 2
      ;;
    --qemu-mem)
      require_value "$1" "$#"
      QEMU_MEM="$2"
      shift 2
      ;;
    --qemu-smp)
      require_value "$1" "$#"
      QEMU_SMP="$2"
      shift 2
      ;;
    --run-id)
      require_value "$1" "$#"
      RUN_ID="$2"
      shift 2
      ;;
    --evidence-dir)
      require_value "$1" "$#"
      EVIDENCE_DIR="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$MANIFEST" ]]; then
  echo "--manifest is required" >&2
  exit 2
fi
MANIFEST="$(canonical_file manifest "$MANIFEST")"
SOURCE_MANIFEST="$MANIFEST"
SCENARIO="$(canonical_file scenario "$SCENARIO")"
SIM_CLI_BIN="$(canonical_file sim-cli "$SIM_CLI_BIN")"
KERNEL_IMAGE="$(canonical_file kernel "$KERNEL_IMAGE")"
INITRAMFS_IMAGE="$(canonical_file initramfs "$INITRAMFS_IMAGE")"
if [[ ! -x "$ARTIFACT_SNAPSHOTTER" ]]; then
  echo "artifact snapshotter is missing or not executable: $ARTIFACT_SNAPSHOTTER" >&2
  exit 2
fi

if [[ "${GENERATION:-}" == "" ]]; then
  GENERATION=$(( $(date +%s) * 1000 + RANDOM ))
fi
for numeric in "$GENERATION" "$TOKEN_VALUE" "$TIMEOUT_MS" "$CNA_BASE" \
               "$ELEMENTS" \
               "$MAX_RUNTIME" "$QEMU_SMP"; do
  if ! printf '%s\n' "$numeric" | grep -Eq '^(0[xX][0-9a-fA-F]+|[0-9]+)$'; then
    echo "invalid numeric value: $numeric" >&2
    exit 2
  fi
done
GENERATION=$((GENERATION))
TOKEN_VALUE=$((TOKEN_VALUE))
TIMEOUT_MS=$((TIMEOUT_MS))
CNA_BASE=$((CNA_BASE))
ELEMENTS=$((ELEMENTS))
MAX_RUNTIME=$((MAX_RUNTIME))
QEMU_SMP=$((QEMU_SMP))
if (( GENERATION == 0 || GENERATION > 281474976710655 ||
      TOKEN_VALUE > 4294967295 || TIMEOUT_MS == 0 || MAX_RUNTIME == 0 ||
      QEMU_SMP == 0 || CNA_BASE == 0 || CNA_BASE + 7 > 0x00ffffff )); then
  echo "numeric option out of range" >&2
  exit 2
fi
if [[ "$LAYOUT" != "nd" || "$ELEMENTS" -ne 16384 ]]; then
  echo "eight-node functional demo requires --layout nd --elements 16384" >&2
  exit 2
fi

python3 - "$MANIFEST" <<'PY'
import json
import sys

with open(sys.argv[1], "r", encoding="utf-8") as stream:
    payload = json.load(stream)
layout = payload.get("ub_gm_layout")
expected = {
    "profile": "nd",
    "global_rows": 128,
    "global_cols": 128,
    "tile_rows": 128,
    "tile_cols": 128,
    "logical_elements": 16384,
}
actual = {key: layout.get(key) for key in expected} if isinstance(layout, dict) else None
if actual != expected:
    raise SystemExit(f"eight-node demo requires ND callable geometry: {actual!r}")
if payload.get("ub_gm_access_fault", "none") != "none":
    raise SystemExit("eight-node demo requires a non-fault callable artifact")
PY

if [[ -z "$EVIDENCE_DIR" ]]; then
  EVIDENCE_DIR="$WORKSPACE_ROOT/out/lingqu-shmem-pto-eight-node/$RUN_ID"
fi
if [[ -e "$EVIDENCE_DIR" ]]; then
  echo "evidence directory already exists: $EVIDENCE_DIR" >&2
  exit 2
fi
mkdir -p "$EVIDENCE_DIR/logs"

MANIFEST="$($ARTIFACT_SNAPSHOTTER \
  --manifest "$SOURCE_MANIFEST" \
  --output-dir "$EVIDENCE_DIR/artifacts")"
MANIFEST="$(canonical_file artifact-snapshot "$MANIFEST")"

FINGERPRINT_JSON="$EVIDENCE_DIR/artifact-fingerprint-before.json"
"$SIM_CLI_BIN" lingqu-shmem-pto-e2e \
  --fingerprint-manifest "$MANIFEST" > "$FINGERPRINT_JSON"
ARTIFACT_FINGERPRINT="$(python3 - "$FINGERPRINT_JSON" <<'PY'
import json
import sys
with open(sys.argv[1], "r", encoding="utf-8") as stream:
    print(json.load(stream)["artifact_fingerprint_hex"])
PY
)"

ROOT_COMMIT="$(git -C "$WORKSPACE_ROOT" rev-parse HEAD)"
RUN_DIR="$GUEST_ROOT/logs/${RUN_ID}_headless8"
ENV_FILE="$GUEST_ROOT/out/headless_eight_node_env.${RUN_ID}.sh"
LAUNCH_STDOUT="$EVIDENCE_DIR/launcher.stdout"
LAUNCH_STDERR="$EVIDENCE_DIR/launcher.stderr"
APPEND_EXTRA="linqu_probe_skip=1 linqu_probe_load_helper=1 pmd_mapping=25%"
APPEND_EXTRA="$APPEND_EXTRA lingqu_shmem_pto_layout=nd"
APPEND_EXTRA="$APPEND_EXTRA lingqu_shmem_pto_elements=$ELEMENTS"
APPEND_EXTRA="$APPEND_EXTRA lingqu_shmem_pto_generation=$GENERATION"
APPEND_EXTRA="$APPEND_EXTRA lingqu_shmem_pto_token_value=$TOKEN_VALUE"
APPEND_EXTRA="$APPEND_EXTRA lingqu_shmem_pto_timeout_ms=$TIMEOUT_MS"
APPEND_EXTRA="$APPEND_EXTRA lingqu_shmem_pto_cancel_after_ms=0"
APPEND_EXTRA="$APPEND_EXTRA lingqu_shmem_pto_expect=success"
APPEND_EXTRA="$APPEND_EXTRA lingqu_shmem_pto_fault_case=none"
APPEND_EXTRA="$APPEND_EXTRA lingqu_shmem_pto_artifact_fingerprint=$ARTIFACT_FINGERPRINT"

RUNNER_RC=0
CLEANUP_SCRIPT=""
typeset -A CAMPAIGN_PIDS
env \
  RUN_ID="$RUN_ID" \
  ENV_FILE="$ENV_FILE" \
  KERNEL_IMAGE="$KERNEL_IMAGE" \
  INITRAMFS_IMAGE="$INITRAMFS_IMAGE" \
  SIM_W5_CLUSTER_NODE_COUNT=8 \
  SIM_UAPI_SCENARIO_CONFIG="$SCENARIO" \
  SIMPLER_HOST_VECTOR_MANIFEST="$MANIFEST" \
  SIM_LINGQU_SHMEM_PTO_ENABLE=1 \
  SIM_LINGQU_SHMEM_PTO_CNA_BASE="$CNA_BASE" \
  QEMU_MEM="$QEMU_MEM" \
  QEMU_SMP="$QEMU_SMP" \
  APPEND_EXTRA="$APPEND_EXTRA" \
  "$LAUNCHER" > "$LAUNCH_STDOUT" 2> "$LAUNCH_STDERR" || RUNNER_RC=$?

if [[ "$RUNNER_RC" -eq 0 && -f "$ENV_FILE" ]]; then
  source "$ENV_FILE"
  for node in A B C D E F G H; do
    pid_file_name="NODE${node}_QEMU_PID_FILE"
    pid_file="${(P)pid_file_name:-}"
    if [[ -n "$pid_file" && -f "$pid_file" ]]; then
      CAMPAIGN_PIDS[$node]="$(tr -d '[:space:]' < "$pid_file")"
    fi
  done
else
  RUNNER_RC=1
fi

if [[ "$RUNNER_RC" -eq 0 ]]; then
  deadline=$((SECONDS + MAX_RUNTIME))
  for node_name in nodeA nodeB nodeC nodeD nodeE nodeF nodeG nodeH; do
    guest_log="$RUN_DIR/${node_name}_guest.log"
    if [[ "$node_name" == "nodeA" ]]; then
      pass_pattern='LINGQU_SHMEM_PTO_RESULT role=producer status=pass consumers=7 lanes_verified=7 completion_acks=7'
    else
      pass_pattern='LINGQU_SHMEM_PTO_RESULT role=consumer status=pass'
    fi
    while (( SECONDS < deadline )); do
      if [[ -f "$guest_log" ]] && grep -q "$pass_pattern" "$guest_log"; then
        break
      fi
      if [[ -f "$guest_log" ]] && grep -q 'LINGQU_SHMEM_PTO_RESULT .*status=fail' "$guest_log"; then
        RUNNER_RC=20
        break
      fi
      sleep 0.2
    done
    if [[ "$RUNNER_RC" -ne 0 ]]; then
      break
    fi
    if [[ ! -f "$guest_log" ]] || ! grep -q "$pass_pattern" "$guest_log"; then
      RUNNER_RC=21
      break
    fi
  done
fi

if [[ -n "${CLEANUP_SCRIPT:-}" && -x "$CLEANUP_SCRIPT" ]]; then
  "$CLEANUP_SCRIPT" > "$EVIDENCE_DIR/cleanup.stdout" 2> "$EVIDENCE_DIR/cleanup.stderr" || {
    if [[ "$RUNNER_RC" -eq 0 ]]; then
      RUNNER_RC=22
    fi
  }
fi
sleep 1
for node_name in nodeA nodeB nodeC nodeD nodeE nodeF nodeG nodeH; do
  for kind in guest qemu; do
    source_log="$RUN_DIR/${node_name}_${kind}.log"
    if [[ -f "$source_log" ]]; then
      cp "$source_log" "$EVIDENCE_DIR/logs/${node_name}_${kind}.log"
    fi
  done
done

QEMU_LEFTOVERS="$EVIDENCE_DIR/qemu-leftovers.txt"
: > "$QEMU_LEFTOVERS"
for node in A B C D E F G H; do
  pid="${CAMPAIGN_PIDS[$node]:-}"
  if [[ "$pid" == <-> ]] && kill -0 "$pid" 2>/dev/null; then
    ps -p "$pid" -o pid=,stat=,command= >> "$QEMU_LEFTOVERS" 2>/dev/null || true
  fi
done
if [[ -s "$QEMU_LEFTOVERS" && "$RUNNER_RC" -eq 0 ]]; then
  RUNNER_RC=23
fi

FINGERPRINT_AFTER_JSON="$EVIDENCE_DIR/artifact-fingerprint-after.json"
"$SIM_CLI_BIN" lingqu-shmem-pto-e2e \
  --fingerprint-manifest "$MANIFEST" > "$FINGERPRINT_AFTER_JSON" || RUNNER_RC=24
ARTIFACT_FINGERPRINT_AFTER="$(python3 - "$FINGERPRINT_AFTER_JSON" <<'PY'
import json
import sys
try:
    with open(sys.argv[1], "r", encoding="utf-8") as stream:
        print(json.load(stream)["artifact_fingerprint_hex"])
except Exception:
    print("invalid")
PY
)"
if [[ "$ARTIFACT_FINGERPRINT_AFTER" != "$ARTIFACT_FINGERPRINT" &&
      "$RUNNER_RC" -eq 0 ]]; then
  RUNNER_RC=25
fi
if [[ "$ARTIFACT_FINGERPRINT_AFTER" == "$ARTIFACT_FINGERPRINT" ]]; then
  ARTIFACT_FINGERPRINT_STABLE=1
else
  ARTIFACT_FINGERPRINT_STABLE=0
fi

VALIDATION_JSON="$EVIDENCE_DIR/validation.json"
python3 "$VALIDATOR" \
  --logs-dir "$EVIDENCE_DIR/logs" \
  --output "$VALIDATION_JSON" \
  --run-id "$RUN_ID" \
  --artifact-fingerprint "$ARTIFACT_FINGERPRINT" \
  --cna-base "$CNA_BASE" \
  --root-commit "$ROOT_COMMIT" || {
    if [[ "$RUNNER_RC" -eq 0 ]]; then
      RUNNER_RC=26
    fi
  }

{
  hash_file "$SOURCE_MANIFEST"
  hash_file "$MANIFEST"
  hash_file "$SCENARIO"
  hash_file "$SIM_CLI_BIN"
  hash_file "$KERNEL_IMAGE"
  hash_file "$INITRAMFS_IMAGE"
  if [[ -f "$QEMU_BUILD_DIR/qemu-system-aarch64" ]]; then
    hash_file "$QEMU_BUILD_DIR/qemu-system-aarch64"
  else
    echo "MISSING  $QEMU_BUILD_DIR/qemu-system-aarch64"
  fi
  hash_file "$LAUNCHER"
  hash_file "$VALIDATOR"
  hash_file "$ARTIFACT_SNAPSHOTTER"
  hash_file "$GUEST_ROOT/apps/lingqu_shmem_pto_direct/lingqu_shmem_pto_direct.c"
  hash_file "$GUEST_ROOT/initramfs/run_app"
  while IFS= read -r -d '' artifact; do
    hash_file "$artifact"
  done < <(find "$EVIDENCE_DIR/artifacts" -type f -print0 | sort -z)
} > "$EVIDENCE_DIR/sha256.txt"

{
  echo "root_commit=$ROOT_COMMIT"
  echo "root_status_begin"
  git -C "$WORKSPACE_ROOT" status --short --ignore-submodules=none
  echo "root_status_end"
  echo "submodules_begin"
  git -C "$WORKSPACE_ROOT" submodule status --recursive 2>&1 || true
  echo "submodules_end"
} > "$EVIDENCE_DIR/revisions.txt"

{
  if [[ "$RUNNER_RC" -eq 0 ]]; then
    echo "validation.status=pass"
  else
    echo "validation.status=fail"
  fi
  echo "runner_exit_code=$RUNNER_RC"
  echo "run_id=$RUN_ID"
  echo "root_commit=$ROOT_COMMIT"
  echo "scenario=$SCENARIO"
  echo "source_manifest=$SOURCE_MANIFEST"
  echo "manifest=$MANIFEST"
  echo "artifact_fingerprint=$ARTIFACT_FINGERPRINT"
  echo "artifact_fingerprint_after=$ARTIFACT_FINGERPRINT_AFTER"
  echo "artifact_fingerprint_stable=$ARTIFACT_FINGERPRINT_STABLE"
  echo "nodes=8"
  echo "producer_node=nodeA"
  echo "consumer_nodes=nodeB,nodeC,nodeD,nodeE,nodeF,nodeG,nodeH"
  echo "elements_per_consumer=$ELEMENTS"
  printf 'cna_base=0x%x\n' "$CNA_BASE"
  echo "host_dispatch_serialization=possible"
  echo "host_dispatch_lock=/tmp/linqu_simpler_host_vector.lock"
  echo "qemu_leftovers=$([[ -s "$QEMU_LEFTOVERS" ]] && echo 1 || echo 0)"
} > "$EVIDENCE_DIR/validation.status"

echo "PTO UB_GM eight-node evidence: $EVIDENCE_DIR"
exit "$RUNNER_RC"
