#!/bin/zsh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

SIM_UAPI_W4_CHIPBACKEND_PROFILE="${SIM_UAPI_W4_CHIPBACKEND_PROFILE:-qwen3_dense_0_6b}"
SIM_QWEN3_0_6B_WEIGHTS_PATH="${SIM_QWEN3_0_6B_WEIGHTS_PATH:-/Volumes/repos/qwen3_mlx_run/Qwen3-0.6B}"
SIM_QWEN3_GUEST_DECODE_STEPS="${SIM_QWEN3_GUEST_DECODE_STEPS:-2}"
W4_GUEST_PROGRESS_INTERVAL_SECS="${W4_GUEST_PROGRESS_INTERVAL_SECS:-30}"

export SIM_UAPI_W4_CHIPBACKEND_PROFILE
export SIM_QWEN3_0_6B_WEIGHTS_PATH
export SIM_QWEN3_GUEST_DECODE_STEPS
export W4_GUEST_PROGRESS_INTERVAL_SECS

exec "$SCRIPT_DIR/run_ub_eight_node_w4_guest.sh"
