[package]
name = "sim-models"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
libc = "0.2"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sim-config = { path = "../sim-config" }
sim-core = { path = "../sim-core" }
sim-services = { path = "../sim-services" }
sim-topology = { path = "../sim-topology" }
unicode-normalization = "0.1"
